apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment-sub1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: lembretes-sub1
  template:
    metadata:
      labels:
        app: lembretes-sub1
    spec:
      containers:
        - name: lembretes
          image: asbonato/lembretes:0.0.1
          resources:
            limits:
              memory: 256Mi
              cpu: 1